# Generated by Django 5.0.4 on 2024-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=25)),
            ],
        ),
    ]
