# Generated by Django 5.0.4 on 2024-12-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_supplier_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
