# Generated by Django 5.0.4 on 2024-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
    ]
